//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Product
    {
        public int id { get; set; }
        public int typeid { get; set; }
        public int brandid { get; set; }
        public string proName { get; set; }
        public string BrandName { get; set; }
        public string TypeName { get; set; }
        public int SupID { get; set; }
        public string SupTypeName { get; set; }
    }
}
